import type { AISummary, ExamTarget } from '@/lib/types/data';
import { normalizeAISummary } from '@/lib/types/data';

export interface SummaryExportContext {
  articleTitleEn: string;
  articleTitleZh: string;
  examTarget: ExamTarget;
  summary: AISummary;
}

export function formatSummaryAsPlainText(ctx: SummaryExportContext): string {
  const summary = normalizeAISummary(ctx.summary);
  const lines: string[] = [
    ctx.articleTitleEn,
    ctx.articleTitleZh,
    `Exam target: ${ctx.examTarget}`,
    '',
    '── Summary (EN) ──',
    summary.summary_en,
    '',
    '── Summary (Local) ──',
    summary.summary_local,
  ];

  if (summary.key_points_en?.length) {
    lines.push('', '── Key Points ──');
    summary.key_points_en.forEach((point, i) => {
      lines.push(`${i + 1}. ${point}`);
      const local = summary.key_points_local?.[i];
      if (local) lines.push(`   ${local}`);
    });
  }

  lines.push('', '— Generated by News App AI Summary —');
  return lines.join('\n');
}

export function formatSummaryAsHtml(ctx: SummaryExportContext): string {
  const summary = normalizeAISummary(ctx.summary);
  const keyPointsHtml =
    summary.key_points_en?.length
      ? `<h2>Key Points</h2><ol>${summary.key_points_en
          .map((point, i) => {
            const local = summary.key_points_local?.[i];
            return `<li><p>${escapeHtml(point)}</p>${local ? `<p class="zh">${escapeHtml(local)}</p>` : ''}</li>`;
          })
          .join('')}</ol>`
      : '';

  return `<!DOCTYPE html>
<html lang="zh-Hant">
<head>
  <meta charset="utf-8" />
  <title>${escapeHtml(ctx.articleTitleEn)} — AI Summary</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; max-width: 720px; margin: 2rem auto; padding: 0 1.5rem; color: #1e293b; line-height: 1.6; }
    h1 { font-size: 1.5rem; margin-bottom: 0.25rem; }
    .subtitle { color: #64748b; font-size: 1.1rem; margin-bottom: 1.5rem; }
    .meta { font-size: 0.85rem; color: #94a3b8; margin-bottom: 2rem; }
    h2 { font-size: 0.75rem; text-transform: uppercase; letter-spacing: 0.08em; color: #64748b; margin-top: 1.5rem; }
    .block { background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 12px; padding: 1rem 1.25rem; margin: 0.5rem 0 1rem; }
    .block.zh { background: #eff6ff; border-color: #bfdbfe; }
    ol { padding-left: 1.25rem; }
    li { margin-bottom: 0.75rem; }
  </style>
</head>
<body>
  <h1>${escapeHtml(ctx.articleTitleEn)}</h1>
  <p class="subtitle">${escapeHtml(ctx.articleTitleZh)}</p>
  <p class="meta">Exam target: ${escapeHtml(ctx.examTarget)} · News App AI Summary</p>
  <h2>Summary (EN)</h2>
  <div class="block"><p>${escapeHtml(summary.summary_en).replace(/\n/g, '<br/>')}</p></div>
  <h2>Summary (Local)</h2>
  <div class="block zh"><p>${escapeHtml(summary.summary_local).replace(/\n/g, '<br/>')}</p></div>
  ${keyPointsHtml}
</body>
</html>`;
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

export function downloadTextFile(filename: string, content: string, mime = 'text/plain;charset=utf-8'): void {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

export function openSummaryPrintPdf(ctx: SummaryExportContext): void {
  const html = formatSummaryAsHtml(ctx);
  const win = window.open('', '_blank', 'noopener,noreferrer');
  if (!win) {
    throw new Error('無法開啟列印視窗，請允許彈出視窗後再試。');
  }
  win.document.write(html);
  win.document.close();
  win.focus();
  setTimeout(() => {
    win.print();
  }, 300);
}

export async function copySummaryToClipboard(ctx: SummaryExportContext): Promise<void> {
  const text = formatSummaryAsPlainText(ctx);
  if (!navigator.clipboard?.writeText) {
    throw new Error('此瀏覽器不支援複製到剪貼簿。');
  }
  await navigator.clipboard.writeText(text);
}

export async function shareSummary(ctx: SummaryExportContext): Promise<'shared' | 'copied' | 'cancelled'> {
  const text = formatSummaryAsPlainText(ctx);
  const title = `${ctx.articleTitleEn} — AI 摘要`;

  if (typeof navigator.share === 'function') {
    try {
      await navigator.share({ title, text });
      return 'shared';
    } catch (err) {
      if (err instanceof Error && err.name === 'AbortError') return 'cancelled';
      throw err;
    }
  }

  await copySummaryToClipboard(ctx);
  return 'copied';
}
